In [2]:
import pandas as pd
import numpy as np

In [3]:
#CUSTOMER SEGMENTATION (PURCHASE BEHAVIOUR + CLUSTRING)

In [4]:
##PURCHASE BEHAVIOUR

In [5]:
sales_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Sales_Transactions.csv")
sales_df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
73539,ORD1035951,2025-05-07,HYD-05,CUST008819,SKU00711,4,82.20,43.84,Unknown,Home Delivery,Card,Delivered
73540,ORD1004773,2025-04-28,MUM-01,CUST011280,SKU00814,2,331.11,208.68,Unknown,Home Delivery,Cash,Delivered
73541,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,Unknown,Home Delivery,Card,Delivered
73542,ORD1004513,2025-03-15,CHE-05,CUST009412,SKU00624,1,135.41,0.25,Unknown,Home Delivery,Wallet,Delivered
73543,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,Unknown,Home Delivery,Cash,Delivered

In [6]:
products_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Product_Master.csv")
products_df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1185,SKU01198,AquaFizz Namkeen 250g,Snacks,Namkeen,AquaFizz,12,17.37,25.21
1186,SKU01199,FreshCo Deodorant 1L,Personal Care,Deodorant,FreshCo,18,62.35,82.94
1187,SKU01200,Snackify Toothpaste 500g,Personal Care,Toothpaste,Snackify,18,57.02,98.97
1188,SKU00484,HealthHub Skin Care 500g,Personal Care,Skin Care,HealthHub,18,21.13,36.40
1189,SKU00599,FreshCo Skin Care 2L,Personal Care,Skin Care,FreshCo,18,79.40,139.94

In [7]:
sales_df['Revenue'] = sales_df['Selling_Price'] * sales_df['Quantity']
sales_df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status,Revenue
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,290.92
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered,1641.72
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered,117.90
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered,182.26
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered,243.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73539,ORD1035951,2025-05-07,HYD-05,CUST008819,SKU00711,4,82.20,43.84,Unknown,Home Delivery,Card,Delivered,328.80
73540,ORD1004773,2025-04-28,MUM-01,CUST011280,SKU00814,2,331.11,208.68,Unknown,Home Delivery,Cash,Delivered,662.22
73541,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,Unknown,Home Delivery,Card,Delivered,419.22
73542,ORD1004513,2025-03-15,CHE-05,CUST009412,SKU00624,1,135.41,0.25,Unknown,Home Delivery,Wallet,Delivered,135.41
73543,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,Unknown,Home Delivery,Cash,Delivered,39.18

In [8]:
total_revenue = sales_df['Revenue'].sum()
print(total_revenue)

26158716.54

In [9]:
#Total Spend
total_spend = sales_df.groupby('Customer_ID')['Revenue'].sum()
total_spend

Customer_ID
CUST000001    1512.98
CUST000002    1913.13
CUST000003    1365.46
CUST000004    1123.44
CUST000005     420.03
               ...
CUST014995    1831.61
CUST014996    1886.11
CUST014997     684.64
CUST014999    1159.87
CUST015000    1047.40
Name: Revenue, Length: 14902, dtype: float64

In [10]:
# Order Frequency
order_freq = sales_df.groupby('Customer_ID')['Order_ID'].nunique()
order_freq

Customer_ID
CUST000001    3
CUST000002    9
CUST000003    5
CUST000004    3
CUST000005    2
             ..
CUST014995    6
CUST014996    4
CUST014997    3
CUST014999    5
CUST015000    2
Name: Order_ID, Length: 14902, dtype: int64

In [11]:
# Avg Order Value
aov = total_spend / order_freq
aov

Customer_ID
CUST000001    504.326667
CUST000002    212.570000
CUST000003    273.092000
CUST000004    374.480000
CUST000005    210.015000
                 ...
CUST014995    305.268333
CUST014996    471.527500
CUST014997    228.213333
CUST014999    231.974000
CUST015000    523.700000
Length: 14902, dtype: float64

In [12]:
#Return Frequency

In [13]:
returns_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Returns.csv")
returns_df

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4565,RET1794775,ORD2921470,SKU00191,2025-03-24,Late Delivery,148.43,Approved
4566,RET2924226,ORD4438000,SKU00195,2025-03-26,Damaged,1183.18,Approved
4567,RET8454564,ORD3418454,SKU00447,2025-04-05,Damaged,562.80,Approved
4568,RET6793261,ORD8923464,SKU00699,2025-07-08,Wrong Item,70.34,Approved
4569,RET2451482,ORD8661457,SKU00546,2025-03-05,Wrong Item,736.52,Rejected

In [14]:
merged_df = sales_df.merge(
    returns_df[['SKU_ID', 'Return_ID']],
    on='SKU_ID',
    how='left'
)
merged_df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status,Revenue,Return_ID
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,290.92,RET200470
1,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,290.92,RET201336
2,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,290.92,RET201706
3,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,290.92,RET203822
4,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,290.92,RET203883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277315,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,Unknown,Home Delivery,Card,Delivered,419.22,RET203357
277316,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,Unknown,Home Delivery,Card,Delivered,419.22,RET203794
277317,ORD1004513,2025-03-15,CHE-05,CUST009412,SKU00624,1,135.41,0.25,Unknown,Home Delivery,Wallet,Delivered,135.41,RET201587
277318,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,Unknown,Home Delivery,Cash,Delivered,39.18,RET201012
277319,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,Unknown,Home Delivery,Cash,Delivered,39.18,RET202280

In [16]:
return_freq = merged_df.groupby('Customer_ID')['Return_ID'].count()
return_freq

Customer_ID
CUST000001    11
CUST000002    37
CUST000003    11
CUST000004     9
CUST000005     6
              ..
CUST014995    18
CUST014996    15
CUST014997    11
CUST014999    12
CUST015000     3
Name: Return_ID, Length: 14902, dtype: int64

In [17]:
# Combineing all togeather
customer_df = pd.DataFrame({
    'Total_Spend': total_spend,
    'Order_Frequency': order_freq,
    'Avg_Order_Value': aov,
    'Return_Frequency':return_freq
}).reset_index()
customer_df

,Customer_ID,Total_Spend,Order_Frequency,Avg_Order_Value,Return_Frequency
0,CUST000001,1512.98,3,504.326667,11
1,CUST000002,1913.13,9,212.570000,37
2,CUST000003,1365.46,5,273.092000,11
3,CUST000004,1123.44,3,374.480000,9
4,CUST000005,420.03,2,210.015000,6
...,...,...,...,...,...
14897,CUST014995,1831.61,6,305.268333,18
14898,CUST014996,1886.11,4,471.527500,15
14899,CUST014997,684.64,3,228.213333,11
14900,CUST014999,1159.87,5,231.974000,12
14901,CUST015000,1047.40,2,523.700000,3

In [18]:
##CLUSTRING

In [19]:
from sklearn.preprocessing import StandardScaler

features = ['Total_Spend', 'Order_Frequency', 'Avg_Order_Value', 'Return_Frequency']

scaler = StandardScaler()
scaled_data = scaler.fit_transform(customer_df[features])

In [20]:
def label_segment(row):
    if row['Total_Spend'] > 10000 and row['Order_Frequency'] > 10:
        return 'High Value Loyal'
    elif row['Avg_Order_Value'] < 500 and row['Order_Frequency'] > 5:
        return 'Deal Hunters'
    elif row['Order_Frequency'] == 1:
        return 'One-time Buyers'
    elif row['Return_Frequency'] > 3:
        return 'High Return Risk'
    else:
        return 'Regular Customers'

customer_df['Segment'] = customer_df.apply(label_segment, axis=1)

In [21]:
customer_df.head(10)

,Customer_ID,Total_Spend,Order_Frequency,Avg_Order_Value,Return_Frequency,Segment
0,CUST000001,1512.98,3,504.326667,11,High Return Risk
1,CUST000002,1913.13,9,212.570000,37,Deal Hunters
2,CUST000003,1365.46,5,273.092000,11,High Return Risk
3,CUST000004,1123.44,3,374.480000,9,High Return Risk
4,CUST000005,420.03,2,210.015000,6,High Return Risk
5,CUST000006,619.16,2,309.580000,6,High Return Risk
6,CUST000007,1037.74,4,259.435000,13,High Return Risk
7,CUST000008,1369.20,4,342.300000,16,High Return Risk
8,CUST000009,1624.08,4,406.020000,13,High Return Risk
9,CUST000010,2197.91,5,439.582000,21,High Return Risk

In [22]:
#AUTOMATED INSIGHT REPORT

In [23]:
sales_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Sales_Transactions.csv")
sales_df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
73539,ORD1035951,2025-05-07,HYD-05,CUST008819,SKU00711,4,82.20,43.84,Unknown,Home Delivery,Card,Delivered
73540,ORD1004773,2025-04-28,MUM-01,CUST011280,SKU00814,2,331.11,208.68,Unknown,Home Delivery,Cash,Delivered
73541,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,Unknown,Home Delivery,Card,Delivered
73542,ORD1004513,2025-03-15,CHE-05,CUST009412,SKU00624,1,135.41,0.25,Unknown,Home Delivery,Wallet,Delivered
73543,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,Unknown,Home Delivery,Cash,Delivered

In [24]:
returns_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Returns.csv")
returns_df

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4565,RET1794775,ORD2921470,SKU00191,2025-03-24,Late Delivery,148.43,Approved
4566,RET2924226,ORD4438000,SKU00195,2025-03-26,Damaged,1183.18,Approved
4567,RET8454564,ORD3418454,SKU00447,2025-04-05,Damaged,562.80,Approved
4568,RET6793261,ORD8923464,SKU00699,2025-07-08,Wrong Item,70.34,Approved
4569,RET2451482,ORD8661457,SKU00546,2025-03-05,Wrong Item,736.52,Rejected

In [25]:
products_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Product_Master.csv")
products_df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1185,SKU01198,AquaFizz Namkeen 250g,Snacks,Namkeen,AquaFizz,12,17.37,25.21
1186,SKU01199,FreshCo Deodorant 1L,Personal Care,Deodorant,FreshCo,18,62.35,82.94
1187,SKU01200,Snackify Toothpaste 500g,Personal Care,Toothpaste,Snackify,18,57.02,98.97
1188,SKU00484,HealthHub Skin Care 500g,Personal Care,Skin Care,HealthHub,18,21.13,36.40
1189,SKU00599,FreshCo Skin Care 2L,Personal Care,Skin Care,FreshCo,18,79.40,139.94

In [26]:
vendor_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Vendor_Supply.csv")
vendor_df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost,Supply_Delay_Days,SLA_Breach
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18,2025-03-24,2025-03-31,57,211.19,7,True
1,PO300001,VEND0037,SKU00870,AHM-01,2025-03-16,2025-03-21,2025-03-21,52,155.29,0,False
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15,2025-03-20,2025-03-22,65,78.13,2,True
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03,2025-04-10,2025-04-11,53,59.70,1,True
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04,2025-05-12,2025-05-12,69,51.96,0,False
...,...,...,...,...,...,...,...,...,...,...,...
29360,PO306051,VEND0056,SKU01019,JAI-03,2025-05-05,2025-05-10,2025-05-10,60,27.21,0,False
29361,PO311238,VEND0094,SKU00448,KOC-01,2025-01-24,2025-02-02,2025-02-02,57,123.68,0,False
29362,PO311019,VEND0075,SKU76949,HYD-05,2025-03-18,2025-03-20,2025-03-20,51,103.44,0,False
29363,PO324099,VEND0063,SKU00055,HYD-05,2025-04-01,2025-04-04,2025-04-04,57,27.56,0,False
29364,PO322920,VEND0071,SKU00284,AHM-04,2025-03-12,2025-03-15,2025-03-15,54,90.01,0,False

In [27]:
inventory_df = pd.read_csv(r"C:\Users\pavan_shsjuzl\Downloads\Inventory_Daily.csv")
inventory_df

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92,394
1,2025-01-25,PUN-01,SKU01164,34,54,52,265
2,2025-01-07,AHM-05,SKU00092,31,40,42,324
3,2025-04-24,KOC-02,SKU00453,13,79,79,106
4,2025-02-05,JAI-05,SKU00507,24,107,103,305
...,...,...,...,...,...,...,...
49522,2025-05-25,AHM-03,SKU05347,10,14,11,307
49523,2025-05-09,AHM-03,SKU00851,15,29,0,252
49524,2025-02-23,AHM-04,SKU00205,18,67,66,441
49525,2025-04-18,HYD-04,SKU00942,16,62,0,257
49526,2025-05-02,KOL-05,SKU00031,15,64,0,106

In [28]:
merged_df = sales_df.merge(
    products_df[['SKU_ID', 'Unit_Cost']],
    on='SKU_ID',
    how='left'
)
merged_df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status,Unit_Cost
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,Unknown,Home Delivery,UPI,Delivered,55.80
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered,188.25
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered,45.73
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered,73.14
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered,78.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73601,ORD1035951,2025-05-07,HYD-05,CUST008819,SKU00711,4,82.20,43.84,Unknown,Home Delivery,Card,Delivered,60.47
73602,ORD1004773,2025-04-28,MUM-01,CUST011280,SKU00814,2,331.11,208.68,Unknown,Home Delivery,Cash,Delivered,251.61
73603,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,Unknown,Home Delivery,Card,Delivered,54.49
73604,ORD1004513,2025-03-15,CHE-05,CUST009412,SKU00624,1,135.41,0.25,Unknown,Home Delivery,Wallet,Delivered,91.22
73605,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,Unknown,Home Delivery,Cash,Delivered,16.82

In [29]:
sales_df['Profit'] = (sales_df['Selling_Price'] - merged_df['Unit_Cost']) * sales_df['Quantity']

In [30]:
#Top 5 loss Drivers
loss_drivers = (
    sales_df.groupby('SKU_ID')['Profit']
    .sum()
    .sort_values()
    .head(5)
    .reset_index(name='Total_Loss')
)
loss_drivers

     SKU_ID  Total_Loss
0  SKU00236   -18326.54
1  SKU00906   -17909.51
2  SKU00375   -15668.27
3  SKU00739   -15447.74
4  SKU00256   -15179.07

In [31]:
#Worst 3 Vendors
worst_vendors = (
    vendor_df.groupby('Vendor_ID')['Supply_Delay_Days']
    .mean()
    .sort_values(ascending=False)
    .head(3)
    .reset_index(name='Avg_Delay')
)
worst_vendors

  Vendor_ID  Avg_Delay
0  VEND0100   2.755556
1  VEND0097   2.255230
2  VEND0027   2.096296

In [32]:
#Stockout Hotspots
stockout_hotspots = inventory_df[
    inventory_df['Closing_Stock'] == 0
].groupby('Store_ID').size().reset_index(name='Stockout_Count')

stockout_hotspots = stockout_hotspots.sort_values(
    by='Stockout_Count', ascending=False
).head(5)
stockout_hotspots

   Store_ID  Stockout_Count
14   CHE-05              43
29   JAI-05              43
35   KOL-01              41
23   HYD-04              40
47   PUN-03              37

In [33]:
sales_df['Profit'] = (sales_df['Selling_Price'] - merged_df['Unit_Cost']) * sales_df['Quantity']

In [34]:
best_skus = (
    sales_df.groupby('SKU_ID')['Profit']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .reset_index(name='Total_Profit')
)
best_skus

     SKU_ID  Total_Profit
0  SKU00865     105409.20
1  SKU01184      89095.59
2  SKU00885      72604.95
3  SKU00195      69907.71
4  SKU00409      66896.89

In [35]:
#Instal xlsxwriter
!pip install XlsxWriter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: XlsxWriter in c:\users\pavan_shsjuzl\appdata\roaming\python\python313\site-packages (3.2.9)

In [36]:
#Export Excel Summary
with pd.ExcelWriter("Insights_Report.xlsx", engine='xlsxwriter') as writer:
    loss_drivers.to_excel(writer, sheet_name='Loss_Drivers', index=False)
    worst_vendors.to_excel(writer, sheet_name='Worst_Vendors', index=False)
    stockout_hotspots.to_excel(writer, sheet_name='Stockouts', index=False)
    best_skus.to_excel(writer, sheet_name='Best_SKUs', index=False)

In [38]:
#Generate Executive PDF Report
%pip install reportlab

Defaulting to user installation because normal site-packages is not writeable
Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in c:\programdata\anaconda3\lib\site-packages (from reportlab) (12.0.0)
Requirement already satisfied: charset-normalizer in c:\programdata\anaconda3\lib\site-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   --------------------- ------------------ 1.0/2.0 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 4.6 MB/s  0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.10
Note: you may need to restart the kernel to use updated packages.

In [39]:
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

doc = SimpleDocTemplate("Executive_Report.pdf")
styles = getSampleStyleSheet()

content = []

# Title
content.append(Paragraph("Retail Insights Executive Report", styles['Title']))
content.append(Spacer(1, 12))

# Top Loss Drivers
content.append(Paragraph("Top 5 Loss Drivers", styles['Heading2']))
for i, row in loss_drivers.iterrows():
    text = f"SKU {row['SKU_ID']} → Loss: {row['Total_Loss']}"
    content.append(Paragraph(text, styles['Normal']))
content.append(Spacer(1, 10))

# Worst Vendors
content.append(Paragraph("Worst 3 Vendors", styles['Heading2']))
for i, row in worst_vendors.iterrows():
    text = f"Vendor {row['Vendor_ID']} → Avg Delay: {row['Avg_Delay']} days"
    content.append(Paragraph(text, styles['Normal']))
content.append(Spacer(1, 10))

# Stockouts
content.append(Paragraph("Stockout Hotspots", styles['Heading2']))
for i, row in stockout_hotspots.iterrows():
    text = f"Store {row['Store_ID']} → Stockouts: {row['Stockout_Count']}"
    content.append(Paragraph(text, styles['Normal']))
content.append(Spacer(1, 10))

# Best SKUs
content.append(Paragraph("Best SKUs to Promote", styles['Heading2']))
for i, row in best_skus.iterrows():
    text = f"SKU {row['SKU_ID']} → Profit: {row['Total_Profit']}"
    content.append(Paragraph(text, styles['Normal']))

doc.build(content)