In [ ]:
#SALES_TRANSACTIONS - DATA CLEANING AND EDA

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Sales_Transactions")
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01 00:00:00,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PROMO-9999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14 00:00:00,HYD-03,CUST004865,SKU01082,6,273.62,173.52,NaN,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05 00:00:00,BEN-05,CUST006245,SKU00901,2,58.95,4.42,NaN,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23 00:00:00,JAI-02,CUST009196,SKU00524,2,188.08,23.20,NaN,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01 00:00:00,PUN-01,CUST000981,SKU00215,2,91.13,16.68,NaN,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08 00:00:00,MUM-01,CUST000930,SKU00727,3,41.21,10.77,NaN,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21 00:00:00,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PR0020,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01 00:00:00,PUN-03,CUST009816,SKU00798,6,220.12,222.18,NaN,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10 00:00:00,HYD-02,CUST014782,SKU00777,3,76.19,35.70,NaN,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09 00:00:00,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PR0011,Home Delivery,Card,Delivered

In [3]:
df.info

<bound method DataFrame.info of          Order_ID           Order_Date Store_ID Customer_ID    SKU_ID  \
0      ORD1000000  2025-06-01 00:00:00   HYD-03  CUST007684  SKU00565
1      ORD1000001  2025-03-14 00:00:00   HYD-03  CUST004865  SKU01082
2      ORD1000002  2025-06-05 00:00:00   BEN-05  CUST006245  SKU00901
3      ORD1000003  2025-06-23 00:00:00   JAI-02  CUST009196  SKU00524
4      ORD1000004  2025-03-01 00:00:00   PUN-01  CUST000981  SKU00215
...           ...                  ...      ...         ...       ...
81595  ORD1075800  2025-02-08 00:00:00   MUM-01  CUST000930  SKU00727
81596  ORD1026987  2025-06-21 00:00:00   PUN-03  CUST007112  SKU00621
81597  ORD1005262  2025-01-01 00:00:00   PUN-03  CUST009816  SKU00798
81598  ORD1021709  2025-01-10 00:00:00   HYD-02  CUST014782  SKU00777
81599  ORD1017737  2025-06-09 00:00:00   BEN-01  CUST012250  SKU00290

       Quantity  Selling_Price  Discount_Amount    Promo_ID  Delivery_Type  \
0             4          72.73            19.52  PROMO-9999  Home Delivery
1             6         273.62           173.52         NaN   Store Pickup
2             2          58.95             4.42         NaN   Store Pickup
3             2         188.08            23.20         NaN   Store Pickup
4             2          91.13            16.68         NaN  Home Delivery
...         ...            ...              ...         ...            ...
81595         3          41.21            10.77         NaN  Home Delivery
81596         2         204.85            46.08      PR0020   Store Pickup
81597         6         220.12           222.18         NaN  Home Delivery
81598         3          76.19            35.70         NaN   Store Pickup
81599         1         100.57             3.20      PR0011  Home Delivery

      Payment_Mode Order_Status
0              UPI    Delivered
1             Cash    Delivered
2             Card    Delivered
3              UPI    Cancelled
4             Cash    Delivered
...            ...          ...
81595          UPI    Delivered
81596         Cash    Delivered
81597          UPI    Delivered
81598          UPI    Delivered
81599         Card    Delivered

[81600 rows x 12 columns]>

In [4]:
df.dtypes

Order_ID            object
Order_Date          object
Store_ID            object
Customer_ID         object
SKU_ID              object
Quantity             int64
Selling_Price      float64
Discount_Amount    float64
Promo_ID            object
Delivery_Type       object
Payment_Mode        object
Order_Status        object
dtype: object

In [5]:
df.describe()

           Quantity  Selling_Price  Discount_Amount
count  81600.000000   81274.000000     81274.000000
mean       2.977328     118.729621        49.436727
std        1.462271      79.228383        59.006381
min       -8.000000      10.700000         0.000000
25%        2.000000      63.560000        12.760000
50%        3.000000      99.170000        31.260000
75%        4.000000     153.200000        64.550000
max       12.000000     807.170000      1052.700000

In [6]:
df.shape

(81600, 12)

In [7]:
df.isna().sum()

Order_ID               0
Order_Date             0
Store_ID               0
Customer_ID            0
SKU_ID                 0
Quantity               0
Selling_Price        326
Discount_Amount      326
Promo_ID           51469
Delivery_Type          0
Payment_Mode         326
Order_Status           0
dtype: int64

In [8]:
#Data Cleaning -(formatting date, removing inappropriate dates(612 rows))
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce').dt.date
df = df.dropna(subset=['Order_Date'])
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PROMO-9999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,NaN,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,NaN,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23,JAI-02,CUST009196,SKU00524,2,188.08,23.20,NaN,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,NaN,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,NaN,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PR0020,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,NaN,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,NaN,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PR0011,Home Delivery,Card,Delivered

In [9]:
#Data Cleaning - Formatting and stanadardizing Store_ID
df.loc[:, 'Store_ID'] = (
    df['Store_ID']
    .astype(str)
    .str.upper()
    .str.strip()
    .str.replace('_', '-', regex=False)
    .str.replace(r'([A-Z]+)-?(\d+)', lambda x: f"{x.group(1)}-{int(x.group(2)):02d}", regex=True)
)
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PROMO-9999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,NaN,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,NaN,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23,JAI-02,CUST009196,SKU00524,2,188.08,23.20,NaN,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,NaN,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,NaN,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PR0020,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,NaN,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,NaN,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PR0011,Home Delivery,Card,Delivered

In [10]:
#Data Cleaning - Standardizing Order_ID & SKU_ID by removing "-" between the code
df.loc[:, 'Order_ID'] = df['Order_ID'].astype(str).str.replace('-', '', regex=False)
df.loc[:, 'SKU_ID'] = df['SKU_ID'].astype(str).str.replace('-', '', regex=False)
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PROMO-9999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,NaN,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,NaN,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23,JAI-02,CUST009196,SKU00524,2,188.08,23.20,NaN,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,NaN,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,NaN,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PR0020,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,NaN,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,NaN,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PR0011,Home Delivery,Card,Delivered

In [11]:
# Clean and standardize Promo_ID
clean = df['Promo_ID'].astype(str).str.upper().str.strip()

nums = clean.str.replace(r'[^0-9]', '', regex=True)
nums = nums.str[:3].str.zfill(3)

df.loc[:, 'Promo_ID'] = 'PRO' + nums

df.loc[clean.isin(['', 'NAN', 'NONE']), 'Promo_ID'] = 'Unknown'
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PRO999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23,JAI-02,CUST009196,SKU00524,2,188.08,23.20,Unknown,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,Unknown,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PRO002,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,Unknown,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,Unknown,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PRO001,Home Delivery,Card,Delivered

In [12]:
#Replacing Negative Qty values to "0"
df.loc[df['Quantity'] < 0, 'Quantity'] = 0
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PRO999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000003,2025-06-23,JAI-02,CUST009196,SKU00524,2,188.08,23.20,Unknown,Store Pickup,UPI,Cancelled
4,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
81595,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,Unknown,Home Delivery,UPI,Delivered
81596,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PRO002,Store Pickup,Cash,Delivered
81597,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,Unknown,Home Delivery,UPI,Delivered
81598,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,Unknown,Store Pickup,UPI,Delivered
81599,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PRO001,Home Delivery,Card,Delivered

In [13]:
#Data Cleaning - (Remove rows where order_status is Cancelled)
df = df[df['Order_Status'] != 'Cancelled'].reset_index(drop=True)
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PRO999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
75262,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,Unknown,Home Delivery,UPI,Delivered
75263,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PRO002,Store Pickup,Cash,Delivered
75264,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,Unknown,Home Delivery,UPI,Delivered
75265,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,Unknown,Store Pickup,UPI,Delivered
75266,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PRO001,Home Delivery,Card,Delivered

In [14]:
#Data Cleaning (Removed blank sales values,replace blank discount_amt with "Unknown")
df['Discount_Amount'] = df['Discount_Amount'].fillna(0)
df = df.dropna(subset=['Selling_Price'])
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PRO999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
75262,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,Unknown,Home Delivery,UPI,Delivered
75263,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PRO002,Store Pickup,Cash,Delivered
75264,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,Unknown,Home Delivery,UPI,Delivered
75265,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,Unknown,Store Pickup,UPI,Delivered
75266,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PRO001,Home Delivery,Card,Delivered

In [15]:
#Data Cleaning (Fill blank payment_mode with "Unknown")
df.loc[:,'Payment_Mode'] = df['Payment_Mode'].fillna('Unknown')
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PRO999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
75262,ORD1075800,2025-02-08,MUM-01,CUST000930,SKU00727,3,41.21,10.77,Unknown,Home Delivery,UPI,Delivered
75263,ORD1026987,2025-06-21,PUN-03,CUST007112,SKU00621,2,204.85,46.08,PRO002,Store Pickup,Cash,Delivered
75264,ORD1005262,2025-01-01,PUN-03,CUST009816,SKU00798,6,220.12,222.18,Unknown,Home Delivery,UPI,Delivered
75265,ORD1021709,2025-01-10,HYD-02,CUST014782,SKU00777,3,76.19,35.70,Unknown,Store Pickup,UPI,Delivered
75266,ORD1017737,2025-06-09,BEN-01,CUST012250,SKU00290,1,100.57,3.20,PRO001,Home Delivery,Card,Delivered

In [16]:
df.isna().sum()

Order_ID           0
Order_Date         0
Store_ID           0
Customer_ID        0
SKU_ID             0
Quantity           0
Selling_Price      0
Discount_Amount    0
Promo_ID           0
Delivery_Type      0
Payment_Mode       0
Order_Status       0
dtype: int64

In [17]:
#Data Cleaning - Remove duplicate Order_ID
df = df.drop_duplicates(subset = ['Order_ID'])
df

,Order_ID,Order_Date,Store_ID,Customer_ID,SKU_ID,Quantity,Selling_Price,Discount_Amount,Promo_ID,Delivery_Type,Payment_Mode,Order_Status
0,ORD1000000,2025-06-01,HYD-03,CUST007684,SKU00565,4,72.73,19.52,PRO999,Home Delivery,UPI,Delivered
1,ORD1000001,2025-03-14,HYD-03,CUST004865,SKU01082,6,273.62,173.52,Unknown,Store Pickup,Cash,Delivered
2,ORD1000002,2025-06-05,BEN-05,CUST006245,SKU00901,2,58.95,4.42,Unknown,Store Pickup,Card,Delivered
3,ORD1000004,2025-03-01,PUN-01,CUST000981,SKU00215,2,91.13,16.68,Unknown,Home Delivery,Cash,Delivered
4,ORD1000005,2025-05-02,AHM-02,CUST005962,SKU01171,2,121.66,19.08,Unknown,Store Pickup,UPI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...
74970,ORD1035951,2025-05-07,HYD-05,CUST008819,SKU00711,4,82.20,43.84,Unknown,Home Delivery,Card,Delivered
75003,ORD1004773,2025-04-28,MUM-01,CUST011280,SKU00814,2,331.11,208.68,PRO005,Home Delivery,Cash,Delivered
75074,ORD1013619,2025-01-20,CHE-03,CUST005255,SKU00543,6,69.87,10.14,PRO016,Home Delivery,Card,Delivered
75076,ORD1004513,2025-03-15,CHE-05,CUST009412,SKU00624,1,135.41,0.25,Unknown,Home Delivery,Wallet,Delivered
75134,ORD1055713,2025-06-28,JAI-05,CUST012644,SKU00753,2,19.59,18.08,PRO015,Home Delivery,Cash,Delivered

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.to_excel("Sales_Transactions_ipynb.xlsx", index=False)

In [20]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [21]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Sales_Transactions_ipynb.xlsx", index=False)

In [ ]:
#PRODUCT_MASTER - DATA CLEANING & EDA

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Product_Master")
df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1213,SKU00859,Snackify Floor Cleaner 100g,Home Care,Floor Cleaner,Snackify,18,94.47,166.26
1214,SKU01137,DailyDairy Meat 500g,Frozen,Meat,DailyDairy,18,106.15,149.18
1215,SKU00895,AquaFizz Powder Combo,Baby Care,Powder,AquaFizz,5,44.13,77.21
1216,SKU00364,FrostBite Cheese 1kg,Dairy,Cheese,FrostBite,5,64.02,101.28
1217,SKU00229,Nestora Ice Cream Pack,Frozen,Ice Cream,Nestora,18,142.26,220.64

In [24]:
df.info

<bound method DataFrame.info of         SKU_ID                     SKU_Name   Category   Sub_Category  \
0     SKU00001       Snackify Biscuits 500g     Snacks       Biscuits
1     SKU00002          FreshCo Paneer 250g      Dairy         Paneer
2     SKU00003   DailyDairy Edible Oil 500g  Groceries     Edible Oil
3     SKU00004          Snackify Butter 1kg      Dairy         Butter
4     SKU00005    BabyBloom Detergent 750ml  Home Care      Detergent
...        ...                          ...        ...            ...
1213  SKU00859  Snackify Floor Cleaner 100g  Home Care  Floor Cleaner
1214  SKU01137         DailyDairy Meat 500g     Frozen           Meat
1215  SKU00895        AquaFizz Powder Combo  Baby Care         Powder
1216  SKU00364         FrostBite Cheese 1kg      Dairy         Cheese
1217  SKU00229       Nestora Ice Cream Pack     Frozen      Ice Cream

           Brand  Tax_Percent  Unit_Cost     MRP
0       Snackify           12      55.38   99.00
1        FreshCo            5      43.66   59.06
2     DailyDairy            5      76.77  105.78
3       Snackify            5     144.24  259.33
4      BabyBloom           18     112.73  175.81
...          ...          ...        ...     ...
1213    Snackify           18      94.47  166.26
1214  DailyDairy           18     106.15  149.18
1215    AquaFizz            5      44.13   77.21
1216   FrostBite            5      64.02  101.28
1217     Nestora           18     142.26  220.64

[1218 rows x 8 columns]>

In [25]:
df.dtypes

SKU_ID           object
SKU_Name         object
Category         object
Sub_Category     object
Brand            object
Tax_Percent       int64
Unit_Cost       float64
MRP             float64
dtype: object

In [26]:
df.describe()

       Tax_Percent    Unit_Cost          MRP
count  1218.000000  1206.000000  1218.000000
mean     11.472906    88.618284   135.305525
std       5.656826    56.429851    88.976958
min       5.000000    10.760000    16.390000
25%       5.000000    47.922500    73.557500
50%      12.000000    76.105000   114.445000
75%      18.000000   116.030000   173.465000
max      18.000000   516.910000   807.170000

In [27]:
df.isna().sum()

SKU_ID           0
SKU_Name         0
Category         0
Sub_Category     0
Brand           12
Tax_Percent      0
Unit_Cost       12
MRP              0
dtype: int64

In [28]:
df.shape

(1218, 8)

In [29]:
#Data Cleaning - Standardizing SKU_ID by removing "-" between the code
df.loc[:, 'SKU_ID'] = df['SKU_ID'].astype(str).str.replace('-', '', regex=False)
df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1213,SKU00859,Snackify Floor Cleaner 100g,Home Care,Floor Cleaner,Snackify,18,94.47,166.26
1214,SKU01137,DailyDairy Meat 500g,Frozen,Meat,DailyDairy,18,106.15,149.18
1215,SKU00895,AquaFizz Powder Combo,Baby Care,Powder,AquaFizz,5,44.13,77.21
1216,SKU00364,FrostBite Cheese 1kg,Dairy,Cheese,FrostBite,5,64.02,101.28
1217,SKU00229,Nestora Ice Cream Pack,Frozen,Ice Cream,Nestora,18,142.26,220.64

In [30]:
#Data Cleaning (Fill blanks in category with "Unknown") 
df.loc[:, 'Brand'] = df['Brand'].fillna('Unknown')
df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1213,SKU00859,Snackify Floor Cleaner 100g,Home Care,Floor Cleaner,Snackify,18,94.47,166.26
1214,SKU01137,DailyDairy Meat 500g,Frozen,Meat,DailyDairy,18,106.15,149.18
1215,SKU00895,AquaFizz Powder Combo,Baby Care,Powder,AquaFizz,5,44.13,77.21
1216,SKU00364,FrostBite Cheese 1kg,Dairy,Cheese,FrostBite,5,64.02,101.28
1217,SKU00229,Nestora Ice Cream Pack,Frozen,Ice Cream,Nestora,18,142.26,220.64

In [31]:
# Data Cleaning (Removing rows with blank values in Unit_Price)
df = df.dropna(subset=['Unit_Cost'])
df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1213,SKU00859,Snackify Floor Cleaner 100g,Home Care,Floor Cleaner,Snackify,18,94.47,166.26
1214,SKU01137,DailyDairy Meat 500g,Frozen,Meat,DailyDairy,18,106.15,149.18
1215,SKU00895,AquaFizz Powder Combo,Baby Care,Powder,AquaFizz,5,44.13,77.21
1216,SKU00364,FrostBite Cheese 1kg,Dairy,Cheese,FrostBite,5,64.02,101.28
1217,SKU00229,Nestora Ice Cream Pack,Frozen,Ice Cream,Nestora,18,142.26,220.64

In [32]:
df.isna().sum()

SKU_ID          0
SKU_Name        0
Category        0
Sub_Category    0
Brand           0
Tax_Percent     0
Unit_Cost       0
MRP             0
dtype: int64

In [33]:
df = df.drop_duplicates()
df

,SKU_ID,SKU_Name,Category,Sub_Category,Brand,Tax_Percent,Unit_Cost,MRP
0,SKU00001,Snackify Biscuits 500g,Snacks,Biscuits,Snackify,12,55.38,99.00
1,SKU00002,FreshCo Paneer 250g,Dairy,Paneer,FreshCo,5,43.66,59.06
2,SKU00003,DailyDairy Edible Oil 500g,Groceries,Edible Oil,DailyDairy,5,76.77,105.78
3,SKU00004,Snackify Butter 1kg,Dairy,Butter,Snackify,5,144.24,259.33
4,SKU00005,BabyBloom Detergent 750ml,Home Care,Detergent,BabyBloom,18,112.73,175.81
...,...,...,...,...,...,...,...,...
1197,SKU01198,AquaFizz Namkeen 250g,Snacks,Namkeen,AquaFizz,12,17.37,25.21
1198,SKU01199,FreshCo Deodorant 1L,Personal Care,Deodorant,FreshCo,18,62.35,82.94
1199,SKU01200,Snackify Toothpaste 500g,Personal Care,Toothpaste,Snackify,18,57.02,98.97
1206,SKU00484,HealthHub Skin Care 500g,Personal Care,Skin Care,HealthHub,18,21.13,36.40
1208,SKU00599,FreshCo Skin Care 2L,Personal Care,Skin Care,FreshCo,18,79.40,139.94

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.to_excel("Product_Master_ipynb.xlsx", index=False)

In [36]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [37]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Product_Master_ipynb.xlsx", index=False)

In [ ]:
#INVENTORY_DAILY - DATA CLEANING & EDA

In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Inventory_Daily")
df

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01 00:00:00,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25 00:00:00,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07 00:00:00,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24 00:00:00,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05 00:00:00,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50495,2025-05-27 00:00:00,HYD-05,SKU00677,39,104,103.0,126.0
50496,2025-03-08 00:00:00,HYD-01,SKU00385,33,14,16.0,379.0
50497,2025-03-12 00:00:00,JAI-04,SKU00648,37,68,65.0,448.0
50498,2025-05-07 00:00:00,CHE-03,SKU01064,36,9,4.0,421.0
50499,2025-04-13 00:00:00,BEN-04,SKU00201,31,101,99.0,425.0

In [40]:
df.info

<bound method DataFrame.info of                       Date Store_ID    SKU_ID  Reorder_Level  Opening_Stock  \
0      2025-02-01 00:00:00   MUM-04  SKU01181             10             96
1      2025-01-25 00:00:00   PUN-01  SKU01164             34             54
2      2025-01-07 00:00:00   AHM-05  SKU00092             31             40
3      2025-04-24 00:00:00   KOC-02  SKU00453             13             79
4      2025-02-05 00:00:00   JAI-05  SKU00507             24            107
...                    ...      ...       ...            ...            ...
50495  2025-05-27 00:00:00   HYD-05  SKU00677             39            104
50496  2025-03-08 00:00:00   HYD-01  SKU00385             33             14
50497  2025-03-12 00:00:00   JAI-04  SKU00648             37             68
50498  2025-05-07 00:00:00   CHE-03  SKU01064             36              9
50499  2025-04-13 00:00:00   BEN-04  SKU00201             31            101

       Closing_Stock  Warehouse_Stock
0               92.0            394.0
1               52.0            265.0
2               42.0            324.0
3               79.0            106.0
4              103.0            305.0
...              ...              ...
50495          103.0            126.0
50496           16.0            379.0
50497           65.0            448.0
50498            4.0            421.0
50499           99.0            425.0

[50500 rows x 7 columns]>

In [41]:
df.dtypes

Date                object
Store_ID            object
SKU_ID              object
Reorder_Level        int64
Opening_Stock        int64
Closing_Stock      float64
Warehouse_Stock    float64
dtype: object

In [42]:
df.describe()

       Reorder_Level  Opening_Stock  Closing_Stock  Warehouse_Stock
count   50500.000000   50500.000000   50248.000000     50248.000000
mean       24.522356      59.565366      57.587327       273.891259
std         8.622352      34.638148      34.626195       130.099811
min        10.000000       0.000000       0.000000        50.000000
25%        17.000000      30.000000      28.000000       161.000000
50%        25.000000      60.000000      58.000000       273.000000
75%        32.000000      90.000000      88.000000       387.000000
max        39.000000     119.000000     123.000000       499.000000

In [43]:
df.shape

(50500, 7)

In [44]:
df.isna().sum()

Date                 0
Store_ID             0
SKU_ID               0
Reorder_Level        0
Opening_Stock        0
Closing_Stock      252
Warehouse_Stock    252
dtype: int64

In [45]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.date
df = df.dropna(subset=['Date'])
df

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50495,2025-05-27,HYD-05,SKU00677,39,104,103.0,126.0
50496,2025-03-08,HYD-01,SKU00385,33,14,16.0,379.0
50497,2025-03-12,JAI-04,SKU00648,37,68,65.0,448.0
50498,2025-05-07,CHE-03,SKU01064,36,9,4.0,421.0
50499,2025-04-13,BEN-04,SKU00201,31,101,99.0,425.0

In [46]:
#Data Cleaning - Formatting and stanadardizing Store_ID
df.loc[:, 'Store_ID'] = (
    df['Store_ID']
    .astype(str)
    .str.upper()
    .str.strip()
    .str.replace('_', '-', regex=False)
    .str.replace(r'([A-Z]+)-?(\d+)', lambda x: f"{x.group(1)}-{int(x.group(2)):02d}", regex=True)
)
df

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50495,2025-05-27,HYD-05,SKU00677,39,104,103.0,126.0
50496,2025-03-08,HYD-01,SKU00385,33,14,16.0,379.0
50497,2025-03-12,JAI-04,SKU00648,37,68,65.0,448.0
50498,2025-05-07,CHE-03,SKU01064,36,9,4.0,421.0
50499,2025-04-13,BEN-04,SKU00201,31,101,99.0,425.0

In [47]:
#Data Cleaning - Standardizing SKU_ID by removing "-" between the code
df.loc[:, 'SKU_ID'] = df['SKU_ID'].astype(str).str.replace('-', '', regex=False)
df

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50495,2025-05-27,HYD-05,SKU00677,39,104,103.0,126.0
50496,2025-03-08,HYD-01,SKU00385,33,14,16.0,379.0
50497,2025-03-12,JAI-04,SKU00648,37,68,65.0,448.0
50498,2025-05-07,CHE-03,SKU01064,36,9,4.0,421.0
50499,2025-04-13,BEN-04,SKU00201,31,101,99.0,425.0

In [48]:
df.isna().sum()

Date                 0
Store_ID             0
SKU_ID               0
Reorder_Level        0
Opening_Stock        0
Closing_Stock      250
Warehouse_Stock    250
dtype: int64

In [50]:
#Data Cleaning - Remove blanks in Closing_Stock & Warehouse_Stock with "0"
df.loc[:, 'Closing_Stock'] = df['Closing_Stock'].fillna(0)
df.loc[:, 'Warehouse_Stock'] = df['Warehouse_Stock'].fillna(0)

In [51]:
df.shape

(49995, 7)

In [52]:
df.duplicated().sum()

np.int64(468)

In [53]:
df = df.drop_duplicates()
df

,Date,Store_ID,SKU_ID,Reorder_Level,Opening_Stock,Closing_Stock,Warehouse_Stock
0,2025-02-01,MUM-04,SKU01181,10,96,92.0,394.0
1,2025-01-25,PUN-01,SKU01164,34,54,52.0,265.0
2,2025-01-07,AHM-05,SKU00092,31,40,42.0,324.0
3,2025-04-24,KOC-02,SKU00453,13,79,79.0,106.0
4,2025-02-05,JAI-05,SKU00507,24,107,103.0,305.0
...,...,...,...,...,...,...,...
50450,2025-05-25,AHM-03,SKU05347,10,14,11.0,307.0
50464,2025-05-09,AHM-03,SKU00851,15,29,0.0,252.0
50466,2025-02-23,AHM-04,SKU00205,18,67,66.0,441.0
50483,2025-04-18,HYD-04,SKU00942,16,62,0.0,257.0
50491,2025-05-02,KOL-05,SKU00031,15,64,0.0,106.0

In [54]:
df.to_excel("Inventory_Daily_ipynb.xlsx", index=False)

In [55]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [56]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Inventory_Daily_ipynb.xlsx", index=False)

In [ ]:
#RETURNS - DATA CLEANING & EDA

In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Returns")
df

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11 00:00:00,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29 00:00:00,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02 00:00:00,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19 00:00:00,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17 00:00:00,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4696,RET-1794775,ORD-2921470,SKU00191,2025-03-24 00:00:00,Late Delivery,148.43,Approved
4697,RET-2924226,ORD-4438000,SKU00195,2025-03-26 00:00:00,Damaged,1183.18,Approved
4698,RET-8454564,ORD-3418454,SKU00447,2025-04-05 00:00:00,Damaged,562.80,Approved
4699,RET-6793261,ORD-8923464,SKU00699,2025-07-08 00:00:00,Wrong Item,70.34,Approved
4700,RET-2451482,ORD-8661457,SKU00546,2025-03-05 00:00:00,Wrong Item,736.52,Rejected

In [59]:
df.info

<bound method DataFrame.info of         Return_ID     Order_ID    SKU_ID          Return_Date  Return_Reason  \
0       RET200000   ORD1079072  SKU00780  2025-05-11 00:00:00  Quality Issue
1       RET200001   ORD1032213  SKU00428  2025-06-29 00:00:00  Quality Issue
2       RET200002   ORD1004967  SKU00969  2025-07-02 00:00:00   Changed Mind
3       RET200003   ORD1042110  SKU00300  2025-04-19 00:00:00  Quality Issue
4       RET200004   ORD1005077  SKU00528  2025-01-17 00:00:00  Quality Issue
...           ...          ...       ...                  ...            ...
4696  RET-1794775  ORD-2921470  SKU00191  2025-03-24 00:00:00  Late Delivery
4697  RET-2924226  ORD-4438000  SKU00195  2025-03-26 00:00:00        Damaged
4698  RET-8454564  ORD-3418454  SKU00447  2025-04-05 00:00:00        Damaged
4699  RET-6793261  ORD-8923464  SKU00699  2025-07-08 00:00:00     Wrong Item
4700  RET-2451482  ORD-8661457  SKU00546  2025-03-05 00:00:00     Wrong Item

      Refund_Amount Return_Status
0            187.78      Approved
1             72.06      Approved
2            279.44      Approved
3            195.15      Approved
4            427.84      Approved
...             ...           ...
4696         148.43      Approved
4697        1183.18      Approved
4698         562.80      Approved
4699          70.34      Approved
4700         736.52      Rejected

[4701 rows x 7 columns]>

In [60]:
df.dtypes

Return_ID         object
Order_ID          object
SKU_ID            object
Return_Date       object
Return_Reason     object
Refund_Amount    float64
Return_Status     object
dtype: object

In [61]:
df.describe()

       Refund_Amount
count    4701.000000
mean      355.293878
std       312.588359
min        13.230000
25%       144.690000
50%       263.030000
75%       462.050000
max      3005.610000

In [62]:
df.shape

(4701, 7)

In [63]:
df.isna().sum()

Return_ID         0
Order_ID          0
SKU_ID            0
Return_Date       0
Return_Reason    47
Refund_Amount     0
Return_Status     0
dtype: int64

In [64]:
#Data Cleaning - Standardizing ID's by removing "-" between the code
df.loc[:, 'Return_ID'] = df['Return_ID'].astype(str).str.replace('-', '', regex=False)
df.loc[:, 'Order_ID'] = df['Order_ID'].astype(str).str.replace('-', '', regex=False)
df.loc[:, 'SKU_ID'] = df['SKU_ID'].astype(str).str.replace('-', '', regex=False)
df

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11 00:00:00,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29 00:00:00,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02 00:00:00,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19 00:00:00,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17 00:00:00,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4696,RET1794775,ORD2921470,SKU00191,2025-03-24 00:00:00,Late Delivery,148.43,Approved
4697,RET2924226,ORD4438000,SKU00195,2025-03-26 00:00:00,Damaged,1183.18,Approved
4698,RET8454564,ORD3418454,SKU00447,2025-04-05 00:00:00,Damaged,562.80,Approved
4699,RET6793261,ORD8923464,SKU00699,2025-07-08 00:00:00,Wrong Item,70.34,Approved
4700,RET2451482,ORD8661457,SKU00546,2025-03-05 00:00:00,Wrong Item,736.52,Rejected

In [65]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df['Return_Date'] = pd.to_datetime(df['Return_Date'], errors='coerce').dt.date
df = df.dropna(subset=['Return_Date'])
df

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4696,RET1794775,ORD2921470,SKU00191,2025-03-24,Late Delivery,148.43,Approved
4697,RET2924226,ORD4438000,SKU00195,2025-03-26,Damaged,1183.18,Approved
4698,RET8454564,ORD3418454,SKU00447,2025-04-05,Damaged,562.80,Approved
4699,RET6793261,ORD8923464,SKU00699,2025-07-08,Wrong Item,70.34,Approved
4700,RET2451482,ORD8661457,SKU00546,2025-03-05,Wrong Item,736.52,Rejected

In [66]:
#Data Cleaning (Fill blank Return_Reason with "Unknown")
df.loc[:,'Return_Reason'] = df['Return_Reason'].fillna('Unknown')
df

,Return_ID,Order_ID,SKU_ID,Return_Date,Return_Reason,Refund_Amount,Return_Status
0,RET200000,ORD1079072,SKU00780,2025-05-11,Quality Issue,187.78,Approved
1,RET200001,ORD1032213,SKU00428,2025-06-29,Quality Issue,72.06,Approved
2,RET200002,ORD1004967,SKU00969,2025-07-02,Changed Mind,279.44,Approved
3,RET200003,ORD1042110,SKU00300,2025-04-19,Quality Issue,195.15,Approved
4,RET200004,ORD1005077,SKU00528,2025-01-17,Quality Issue,427.84,Approved
...,...,...,...,...,...,...,...
4696,RET1794775,ORD2921470,SKU00191,2025-03-24,Late Delivery,148.43,Approved
4697,RET2924226,ORD4438000,SKU00195,2025-03-26,Damaged,1183.18,Approved
4698,RET8454564,ORD3418454,SKU00447,2025-04-05,Damaged,562.80,Approved
4699,RET6793261,ORD8923464,SKU00699,2025-07-08,Wrong Item,70.34,Approved
4700,RET2451482,ORD8661457,SKU00546,2025-03-05,Wrong Item,736.52,Rejected

In [67]:
df.isna().sum()

Return_ID        0
Order_ID         0
SKU_ID           0
Return_Date      0
Return_Reason    0
Refund_Amount    0
Return_Status    0
dtype: int64

In [68]:
df.duplicated().sum()

np.int64(84)

In [69]:
df = df.drop_duplicates()

In [70]:
df.to_excel("Returns_ipynb.xlsx", index=False)

In [71]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [72]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Returns_ipynb.xlsx", index=False)

In [ ]:
#VENDORE_SUPPLY - DATA CLEANING & EDA

In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Vendor_Supply")
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18 00:00:00,2025-03-24 00:00:00,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM1,2025-03-16 00:00:00,2025-03-21 00:00:00,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15 00:00:00,2025-03-20 00:00:00,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03 00:00:00,2025-04-10 00:00:00,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24 00:00:00,2025-03-27 00:00:00,2025-03-28 00:00:00,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21 00:00:00,2025-05-27 00:00:00,2025-05-29 00:00:00,76,128.94
30447,PO317992,VEND0089,SKU00452,che01,2025-05-10 00:00:00,2025-05-18 00:00:00,2025-05-18 00:00:00,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22 00:00:00,2025-01-25 00:00:00,2025-01-25 00:00:00,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02 00:00:00,2025-06-08 00:00:00,2025-06-08 00:00:00,65,50.51

In [75]:
df.info

<bound method DataFrame.info of           PO_ID Vendor_ID    SKU_ID Store_ID              PO_Date  \
0      PO300000  VEND0062  SKU00123   DEL-01  2025-03-18 00:00:00
1      PO300001  VEND0037  SKU00870    AHM1   2025-03-16 00:00:00
2      PO300002  VEND0007  SKU00030   KOC-02  2025-03-15 00:00:00
3      PO300003  VEND0056  SKU01069   MUM-05  2025-04-03 00:00:00
4      PO300004  VEND0046  SKU01152   JAI-02  2025-05-04 00:00:00
...         ...       ...       ...      ...                  ...
30445  PO312250  VEND0117  SKU01158   PUN-01  2025-03-24 00:00:00
30446  PO302211  VEND0059  SKU01193   KOL-05  2025-05-21 00:00:00
30447  PO317992  VEND0089  SKU00452    che01  2025-05-10 00:00:00
30448  PO323605  VEND0023  SKU00418   HYD-05  2025-01-22 00:00:00
30449  PO302285  VEND0071  SKU00637   DEL-03  2025-06-02 00:00:00

      Expected_Delivery_Date Actual_Delivery_Date  Supplied_Quantity  \
0        2025-03-24 00:00:00  2025-03-31 00:00:00                 57
1        2025-03-21 00:00:00  2025-03-21 00:00:00                 52
2        2025-03-20 00:00:00  2025-03-22 00:00:00                 65
3        2025-04-10 00:00:00  2025-04-11 00:00:00                 53
4        2025-05-12 00:00:00  2025-05-12 00:00:00                 69
...                      ...                  ...                ...
30445    2025-03-27 00:00:00  2025-03-28 00:00:00                 53
30446    2025-05-27 00:00:00  2025-05-29 00:00:00                 76
30447    2025-05-18 00:00:00  2025-05-18 00:00:00                 65
30448    2025-01-25 00:00:00  2025-01-25 00:00:00                 75
30449    2025-06-08 00:00:00  2025-06-08 00:00:00                 65

       Procurement_Cost
0                211.19
1                155.29
2                 78.13
3                 59.70
4                 51.96
...                 ...
30445             95.79
30446            128.94
30447             48.13
30448            191.83
30449             50.51

[30450 rows x 9 columns]>

In [76]:
df.dtypes

PO_ID                      object
Vendor_ID                  object
SKU_ID                     object
Store_ID                   object
PO_Date                    object
Expected_Delivery_Date     object
Actual_Delivery_Date       object
Supplied_Quantity           int64
Procurement_Cost          float64
dtype: object

In [77]:
df.describe()

       Supplied_Quantity  Procurement_Cost
count       30450.000000      30298.000000
mean           59.965583         91.023856
std             7.090200         58.010590
min            36.000000         10.250000
25%            55.000000         49.250000
50%            60.000000         77.610000
75%            65.000000        118.870000
max            91.000000        567.830000

In [78]:
#Data Cleaning - Standardizing SKU_ID by removing "-" between code and num
df.loc[:, 'SKU_ID'] = df['SKU_ID'].astype(str).str.replace('-', '', regex=False)
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18 00:00:00,2025-03-24 00:00:00,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM1,2025-03-16 00:00:00,2025-03-21 00:00:00,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15 00:00:00,2025-03-20 00:00:00,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03 00:00:00,2025-04-10 00:00:00,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24 00:00:00,2025-03-27 00:00:00,2025-03-28 00:00:00,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21 00:00:00,2025-05-27 00:00:00,2025-05-29 00:00:00,76,128.94
30447,PO317992,VEND0089,SKU00452,che01,2025-05-10 00:00:00,2025-05-18 00:00:00,2025-05-18 00:00:00,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22 00:00:00,2025-01-25 00:00:00,2025-01-25 00:00:00,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02 00:00:00,2025-06-08 00:00:00,2025-06-08 00:00:00,65,50.51

In [79]:
#Data Cleaning - Formatting and stanadardizing Store_ID
df.loc[:, 'Store_ID'] = (
    df['Store_ID']
    .astype(str)
    .str.upper()
    .str.strip()
    .str.replace('_', '-', regex=False)
    .str.replace(r'([A-Z]+)-?(\d+)', lambda x: f"{x.group(1)}-{int(x.group(2)):02d}", regex=True)
)
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18 00:00:00,2025-03-24 00:00:00,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM-01,2025-03-16 00:00:00,2025-03-21 00:00:00,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15 00:00:00,2025-03-20 00:00:00,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03 00:00:00,2025-04-10 00:00:00,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04 00:00:00,2025-05-12 00:00:00,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24 00:00:00,2025-03-27 00:00:00,2025-03-28 00:00:00,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21 00:00:00,2025-05-27 00:00:00,2025-05-29 00:00:00,76,128.94
30447,PO317992,VEND0089,SKU00452,CHE-01,2025-05-10 00:00:00,2025-05-18 00:00:00,2025-05-18 00:00:00,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22 00:00:00,2025-01-25 00:00:00,2025-01-25 00:00:00,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02 00:00:00,2025-06-08 00:00:00,2025-06-08 00:00:00,65,50.51

In [80]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df['PO_Date'] = pd.to_datetime(df['PO_Date'], errors='coerce').dt.date
df = df.dropna(subset=['PO_Date'])
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18,2025-03-24 00:00:00,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM-01,2025-03-16,2025-03-21 00:00:00,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15,2025-03-20 00:00:00,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03,2025-04-10 00:00:00,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04,2025-05-12 00:00:00,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24,2025-03-27 00:00:00,2025-03-28 00:00:00,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21,2025-05-27 00:00:00,2025-05-29 00:00:00,76,128.94
30447,PO317992,VEND0089,SKU00452,CHE-01,2025-05-10,2025-05-18 00:00:00,2025-05-18 00:00:00,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22,2025-01-25 00:00:00,2025-01-25 00:00:00,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02,2025-06-08 00:00:00,2025-06-08 00:00:00,65,50.51

In [81]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df.loc[:,'Expected_Delivery_Date'] = pd.to_datetime(df['Expected_Delivery_Date'], errors='coerce').dt.date
df = df.dropna(subset=['Expected_Delivery_Date'])
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18,2025-03-24,2025-03-31 00:00:00,57,211.19
1,PO300001,VEND0037,SKU00870,AHM-01,2025-03-16,2025-03-21,2025-03-21 00:00:00,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15,2025-03-20,2025-03-22 00:00:00,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03,2025-04-10,2025-04-11 00:00:00,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04,2025-05-12,2025-05-12 00:00:00,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24,2025-03-27,2025-03-28 00:00:00,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21,2025-05-27,2025-05-29 00:00:00,76,128.94
30447,PO317992,VEND0089,SKU00452,CHE-01,2025-05-10,2025-05-18,2025-05-18 00:00:00,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22,2025-01-25,2025-01-25 00:00:00,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02,2025-06-08,2025-06-08 00:00:00,65,50.51

In [82]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df.loc[:,'Actual_Delivery_Date'] = pd.to_datetime(df['Actual_Delivery_Date'], errors='coerce').dt.date
df = df.dropna(subset=['Actual_Delivery_Date'])
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18,2025-03-24,2025-03-31,57,211.19
1,PO300001,VEND0037,SKU00870,AHM-01,2025-03-16,2025-03-21,2025-03-21,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15,2025-03-20,2025-03-22,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03,2025-04-10,2025-04-11,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04,2025-05-12,2025-05-12,69,51.96
...,...,...,...,...,...,...,...,...,...
30445,PO312250,VEND0117,SKU01158,PUN-01,2025-03-24,2025-03-27,2025-03-28,53,95.79
30446,PO302211,VEND0059,SKU01193,KOL-05,2025-05-21,2025-05-27,2025-05-29,76,128.94
30447,PO317992,VEND0089,SKU00452,CHE-01,2025-05-10,2025-05-18,2025-05-18,65,48.13
30448,PO323605,VEND0023,SKU00418,HYD-05,2025-01-22,2025-01-25,2025-01-25,75,191.83
30449,PO302285,VEND0071,SKU00637,DEL-03,2025-06-02,2025-06-08,2025-06-08,65,50.51

In [83]:
#Data Cleaning - Fill blanks using Median
df.loc[:, 'Procurement_Cost'] = df['Procurement_Cost'].fillna(df['Procurement_Cost'].median())

In [84]:
df.duplicated().sum()

np.int64(408)

In [85]:
df = df.drop_duplicates()
df

,PO_ID,Vendor_ID,SKU_ID,Store_ID,PO_Date,Expected_Delivery_Date,Actual_Delivery_Date,Supplied_Quantity,Procurement_Cost
0,PO300000,VEND0062,SKU00123,DEL-01,2025-03-18,2025-03-24,2025-03-31,57,211.19
1,PO300001,VEND0037,SKU00870,AHM-01,2025-03-16,2025-03-21,2025-03-21,52,155.29
2,PO300002,VEND0007,SKU00030,KOC-02,2025-03-15,2025-03-20,2025-03-22,65,78.13
3,PO300003,VEND0056,SKU01069,MUM-05,2025-04-03,2025-04-10,2025-04-11,53,59.70
4,PO300004,VEND0046,SKU01152,JAI-02,2025-05-04,2025-05-12,2025-05-12,69,51.96
...,...,...,...,...,...,...,...,...,...
30372,PO306051,VEND0056,SKU01019,JAI-03,2025-05-05,2025-05-10,2025-05-10,60,27.21
30373,PO311238,VEND0094,SKU00448,KOC-01,2025-01-24,2025-02-02,2025-02-02,57,123.68
30378,PO311019,VEND0075,SKU76949,HYD-05,2025-03-18,2025-03-20,2025-03-20,51,103.44
30427,PO324099,VEND0063,SKU00055,HYD-05,2025-04-01,2025-04-04,2025-04-04,57,27.56
30429,PO322920,VEND0071,SKU00284,AHM-04,2025-03-12,2025-03-15,2025-03-15,54,90.01

In [86]:
df.to_excel("Vendor_Supply_ipynb.xlsx", index=False)

In [87]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [88]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Vendor_Supply_ipynb.xlsx", index=False)

In [ ]:
#PROMOTIONS - DATA CLEANING & EDA

In [89]:
import pandas as pd
import numpy as np

In [90]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Promotions")
df

,Promo_ID,Promo_Type,Start_Date,End_Date,Target_Category,Promo_Budget
0,PR0001,Flat %,2025-05-28 00:00:00,2025-06-07 00:00:00,Beverages,196431.0
1,PR0002,Flat %,2025-06-13 00:00:00,2025-06-28 00:00:00,Home Care,123013.0
2,PR0003,Flat %,2025-06-10 00:00:00,2025-07-07 00:00:00,Home Care,388105.0
3,PR0004,Member Exclusive,2025-04-06 00:00:00,2025-04-25 00:00:00,Personal Care,254481.0
4,PR0005,Flat %,2025-03-10 00:00:00,2025-04-01 00:00:00,Frozen,63424.0
...,...,...,...,...,...,...
205,PR0021,Member Exclusive,2025-03-12 00:00:00,2025-03-20 00:00:00,Frozen,236449.0
206,PR0200,Member Exclusive,2025-01-27 00:00:00,2025-02-15 00:00:00,Beverages,90374.0
207,PR0009,Member Exclusive,2025-04-30 00:00:00,2025-05-11 00:00:00,Baby Care,778423.0
208,PR0040,BOGO,2025-06-10 00:00:00,2025-06-30 00:00:00,Personal Care,782218.0
209,PR0089,Flat %,2025-02-06 00:00:00,2025-03-03 00:00:00,Baby Care,396667.0

In [91]:
df.info

<bound method DataFrame.info of     Promo_ID        Promo_Type           Start_Date             End_Date  \
0     PR0001            Flat %  2025-05-28 00:00:00  2025-06-07 00:00:00
1     PR0002            Flat %  2025-06-13 00:00:00  2025-06-28 00:00:00
2     PR0003            Flat %  2025-06-10 00:00:00  2025-07-07 00:00:00
3     PR0004  Member Exclusive  2025-04-06 00:00:00  2025-04-25 00:00:00
4     PR0005            Flat %  2025-03-10 00:00:00  2025-04-01 00:00:00
..       ...               ...                  ...                  ...
205   PR0021  Member Exclusive  2025-03-12 00:00:00  2025-03-20 00:00:00
206   PR0200  Member Exclusive  2025-01-27 00:00:00  2025-02-15 00:00:00
207   PR0009  Member Exclusive  2025-04-30 00:00:00  2025-05-11 00:00:00
208   PR0040              BOGO  2025-06-10 00:00:00  2025-06-30 00:00:00
209   PR0089            Flat %  2025-02-06 00:00:00  2025-03-03 00:00:00

    Target_Category  Promo_Budget
0         Beverages      196431.0
1         Home Care      123013.0
2         Home Care      388105.0
3     Personal Care      254481.0
4            Frozen       63424.0
..              ...           ...
205          Frozen      236449.0
206       Beverages       90374.0
207       Baby Care      778423.0
208   Personal Care      782218.0
209       Baby Care      396667.0

[210 rows x 6 columns]>

In [92]:
df.dtypes

Promo_ID            object
Promo_Type          object
Start_Date          object
End_Date            object
Target_Category     object
Promo_Budget       float64
dtype: object

In [93]:
df.describe()

        Promo_Budget
count     206.000000
mean   441237.980583
std    219813.931257
min     54033.000000
25%    262793.750000
50%    447621.000000
75%    647053.750000
max    794126.000000

In [94]:
#Data Cleaning - Fixing ananomus Promo_ID with "Unknown"
df.loc[df['Promo_ID'] == 'PROMO_XXXX', 'Promo_ID'] = 'Unknown'
df

,Promo_ID,Promo_Type,Start_Date,End_Date,Target_Category,Promo_Budget
0,PR0001,Flat %,2025-05-28 00:00:00,2025-06-07 00:00:00,Beverages,196431.0
1,PR0002,Flat %,2025-06-13 00:00:00,2025-06-28 00:00:00,Home Care,123013.0
2,PR0003,Flat %,2025-06-10 00:00:00,2025-07-07 00:00:00,Home Care,388105.0
3,PR0004,Member Exclusive,2025-04-06 00:00:00,2025-04-25 00:00:00,Personal Care,254481.0
4,PR0005,Flat %,2025-03-10 00:00:00,2025-04-01 00:00:00,Frozen,63424.0
...,...,...,...,...,...,...
205,PR0021,Member Exclusive,2025-03-12 00:00:00,2025-03-20 00:00:00,Frozen,236449.0
206,PR0200,Member Exclusive,2025-01-27 00:00:00,2025-02-15 00:00:00,Beverages,90374.0
207,PR0009,Member Exclusive,2025-04-30 00:00:00,2025-05-11 00:00:00,Baby Care,778423.0
208,PR0040,BOGO,2025-06-10 00:00:00,2025-06-30 00:00:00,Personal Care,782218.0
209,PR0089,Flat %,2025-02-06 00:00:00,2025-03-03 00:00:00,Baby Care,396667.0

In [95]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df['Start_Date'] = pd.to_datetime(df['Start_Date'], errors='coerce').dt.date
df = df.dropna(subset=['Start_Date'])
df

,Promo_ID,Promo_Type,Start_Date,End_Date,Target_Category,Promo_Budget
0,PR0001,Flat %,2025-05-28,2025-06-07 00:00:00,Beverages,196431.0
1,PR0002,Flat %,2025-06-13,2025-06-28 00:00:00,Home Care,123013.0
2,PR0003,Flat %,2025-06-10,2025-07-07 00:00:00,Home Care,388105.0
3,PR0004,Member Exclusive,2025-04-06,2025-04-25 00:00:00,Personal Care,254481.0
4,PR0005,Flat %,2025-03-10,2025-04-01 00:00:00,Frozen,63424.0
...,...,...,...,...,...,...
205,PR0021,Member Exclusive,2025-03-12,2025-03-20 00:00:00,Frozen,236449.0
206,PR0200,Member Exclusive,2025-01-27,2025-02-15 00:00:00,Beverages,90374.0
207,PR0009,Member Exclusive,2025-04-30,2025-05-11 00:00:00,Baby Care,778423.0
208,PR0040,BOGO,2025-06-10,2025-06-30 00:00:00,Personal Care,782218.0
209,PR0089,Flat %,2025-02-06,2025-03-03 00:00:00,Baby Care,396667.0

In [96]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df.loc[:,'End_Date'] = pd.to_datetime(df['End_Date'], errors='coerce').dt.date
df = df.dropna(subset=['End_Date'])
df

,Promo_ID,Promo_Type,Start_Date,End_Date,Target_Category,Promo_Budget
0,PR0001,Flat %,2025-05-28,2025-06-07,Beverages,196431.0
1,PR0002,Flat %,2025-06-13,2025-06-28,Home Care,123013.0
2,PR0003,Flat %,2025-06-10,2025-07-07,Home Care,388105.0
3,PR0004,Member Exclusive,2025-04-06,2025-04-25,Personal Care,254481.0
4,PR0005,Flat %,2025-03-10,2025-04-01,Frozen,63424.0
...,...,...,...,...,...,...
205,PR0021,Member Exclusive,2025-03-12,2025-03-20,Frozen,236449.0
206,PR0200,Member Exclusive,2025-01-27,2025-02-15,Beverages,90374.0
207,PR0009,Member Exclusive,2025-04-30,2025-05-11,Baby Care,778423.0
208,PR0040,BOGO,2025-06-10,2025-06-30,Personal Care,782218.0
209,PR0089,Flat %,2025-02-06,2025-03-03,Baby Care,396667.0

In [97]:
#Data Cleaning - Replacing blanks with "0"
df.loc[:, 'Promo_Budget'] = df['Promo_Budget'].fillna(0)

In [98]:
df.duplicated().sum()

np.int64(8)

In [99]:
df = df.drop_duplicates()
df

,Promo_ID,Promo_Type,Start_Date,End_Date,Target_Category,Promo_Budget
0,PR0001,Flat %,2025-05-28,2025-06-07,Beverages,196431.0
1,PR0002,Flat %,2025-06-13,2025-06-28,Home Care,123013.0
2,PR0003,Flat %,2025-06-10,2025-07-07,Home Care,388105.0
3,PR0004,Member Exclusive,2025-04-06,2025-04-25,Personal Care,254481.0
4,PR0005,Flat %,2025-03-10,2025-04-01,Frozen,63424.0
...,...,...,...,...,...,...
197,PR0198,BOGO,2025-01-02,2025-01-26,Beverages,447676.0
198,PR0199,Flat %,2025-01-21,2025-02-06,Home Care,587757.0
199,PR0200,Member Exclusive,2025-01-27,2025-02-15,Beverages,0.0
200,PR0113,Member Exclusive,2025-01-18,2025-01-26,Beverages,748977.0
206,PR0200,Member Exclusive,2025-01-27,2025-02-15,Beverages,90374.0

In [100]:
df.to_excel("Promotions_ipynb.xlsx", index=False)

In [101]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [102]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Promotions_ipynb.xlsx", index=False)

In [ ]:
#CUSTOMER_MASTER - DATA CLEANING & EDA

In [103]:
import pandas as pd
import numpy as np

In [104]:
df = pd.read_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\1.Raw Data\Retail_Profit_Leakage_Dataset.xlsx",
sheet_name="Customer_Master")
df

      Customer_ID       City          Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22 00:00:00           New
1      CUST000002     Mumbai  2025-04-19 00:00:00           New
2      CUST000003  Ahmedabad  2025-03-31 00:00:00     Returning
3      CUST000004      Delhi  2025-01-21 00:00:00     Returning
4      CUST000005  Hyderabad  2025-01-26 00:00:00     Returning
...           ...        ...                  ...           ...
15295  CUST013214      Delhi  2025-01-17 00:00:00           New
15296  CUST000609  Hyderabad  2025-05-25 00:00:00           New
15297  CUST004885  Ahmedabad  2025-05-19 00:00:00           New
15298  CUST013475     Jaipur  2025-01-07 00:00:00           New
15299  CUST004331  Bengaluru  2025-05-22 00:00:00           New

[15300 rows x 4 columns]

In [105]:
df.info

<bound method DataFrame.info of       Customer_ID       City          Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22 00:00:00           New
1      CUST000002     Mumbai  2025-04-19 00:00:00           New
2      CUST000003  Ahmedabad  2025-03-31 00:00:00     Returning
3      CUST000004      Delhi  2025-01-21 00:00:00     Returning
4      CUST000005  Hyderabad  2025-01-26 00:00:00     Returning
...           ...        ...                  ...           ...
15295  CUST013214      Delhi  2025-01-17 00:00:00           New
15296  CUST000609  Hyderabad  2025-05-25 00:00:00           New
15297  CUST004885  Ahmedabad  2025-05-19 00:00:00           New
15298  CUST013475     Jaipur  2025-01-07 00:00:00           New
15299  CUST004331  Bengaluru  2025-05-22 00:00:00           New

[15300 rows x 4 columns]>

In [106]:
df.dtypes

Customer_ID      object
City             object
Signup_Date      object
Customer_Type    object
dtype: object

In [107]:
df.describe()

       Customer_ID       City Signup_Date Customer_Type
count        15300      15147       15300         15300
unique       15016         10         203             3
top     CUST009412  Bengaluru  32/13/2025           New
freq             2       2147         153          9117

In [108]:
df.shape

(15300, 4)

In [109]:
df.isna().sum()

Customer_ID        0
City             153
Signup_Date        0
Customer_Type      0
dtype: int64

In [110]:
#Data Cleaning - Standardizing Customer_ID values
df.loc[:, 'Customer_ID'] = df['Customer_ID'].astype(str).str.replace('-', '', regex=False)
df

      Customer_ID       City          Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22 00:00:00           New
1      CUST000002     Mumbai  2025-04-19 00:00:00           New
2      CUST000003  Ahmedabad  2025-03-31 00:00:00     Returning
3      CUST000004      Delhi  2025-01-21 00:00:00     Returning
4      CUST000005  Hyderabad  2025-01-26 00:00:00     Returning
...           ...        ...                  ...           ...
15295  CUST013214      Delhi  2025-01-17 00:00:00           New
15296  CUST000609  Hyderabad  2025-05-25 00:00:00           New
15297  CUST004885  Ahmedabad  2025-05-19 00:00:00           New
15298  CUST013475     Jaipur  2025-01-07 00:00:00           New
15299  CUST004331  Bengaluru  2025-05-22 00:00:00           New

[15300 rows x 4 columns]

In [111]:
#Data Cleaning (Fill blank City with "Unknown")
df.loc[:,'City'] = df['City'].fillna('Unknown')
df

      Customer_ID       City          Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22 00:00:00           New
1      CUST000002     Mumbai  2025-04-19 00:00:00           New
2      CUST000003  Ahmedabad  2025-03-31 00:00:00     Returning
3      CUST000004      Delhi  2025-01-21 00:00:00     Returning
4      CUST000005  Hyderabad  2025-01-26 00:00:00     Returning
...           ...        ...                  ...           ...
15295  CUST013214      Delhi  2025-01-17 00:00:00           New
15296  CUST000609  Hyderabad  2025-05-25 00:00:00           New
15297  CUST004885  Ahmedabad  2025-05-19 00:00:00           New
15298  CUST013475     Jaipur  2025-01-07 00:00:00           New
15299  CUST004331  Bengaluru  2025-05-22 00:00:00           New

[15300 rows x 4 columns]

In [112]:
df.isna().sum()

Customer_ID      0
City             0
Signup_Date      0
Customer_Type    0
dtype: int64

In [113]:
#Data Cleaning -(formatting date, removing inappropriate dates)
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'], errors='coerce').dt.date
df = df.dropna(subset=['Signup_Date'])
df

      Customer_ID       City Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22           New
1      CUST000002     Mumbai  2025-04-19           New
2      CUST000003  Ahmedabad  2025-03-31     Returning
3      CUST000004      Delhi  2025-01-21     Returning
4      CUST000005  Hyderabad  2025-01-26     Returning
...           ...        ...         ...           ...
15295  CUST013214      Delhi  2025-01-17           New
15296  CUST000609  Hyderabad  2025-05-25           New
15297  CUST004885  Ahmedabad  2025-05-19           New
15298  CUST013475     Jaipur  2025-01-07           New
15299  CUST004331  Bengaluru  2025-05-22           New

[15147 rows x 4 columns]

In [114]:
df.duplicated().sum()

np.int64(264)

In [115]:
df = df.drop_duplicates()
df

      Customer_ID       City Signup_Date Customer_Type
0      CUST000001     Mumbai  2025-04-22           New
1      CUST000002     Mumbai  2025-04-19           New
2      CUST000003  Ahmedabad  2025-03-31     Returning
3      CUST000004      Delhi  2025-01-21     Returning
4      CUST000005  Hyderabad  2025-01-26     Returning
...           ...        ...         ...           ...
15253  CUST011637      Kochi  2025-01-14     Returning
15257  CUST877828    Chennai  2025-02-24           New
15278  CUST482562    Chennai  2025-04-28           New
15286  CUST066492  Bengaluru  2025-03-01           New
15298  CUST013475     Jaipur  2025-01-07           New

[14883 rows x 4 columns]

In [116]:
df.to_excel("Customer_Master_ipynb.xlsx", index=False)

In [117]:
import os
print(os.path.expanduser("~"))

C:\Users\pavan_shsjuzl

In [118]:
df.to_excel(r"C:\Users\pavan_shsjuzl\Downloads\Retail Chain Profit Leakage & Demand Optimization\Data\Customer_Master_ipynb.xlsx", index=False)